# -*- coding: utf-8 -*-
"""GOPIGAA G-583223104030

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lKqj2Jf37kKvak-2noz4K_zcIFrYZHRi

# **TITANIC ANALYSIS**
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import plotly.express as px

ds=pd.read_csv(r"/content/titanic.csv")
print(ds)

print(ds.head())

ds["Fare"]=ds["Fare"].fillna(ds["Fare"].mean())
print(ds)

ds["Age"]=ds["Age"].fillna(ds["Age"].mean())
print(ds)

ds["PassengerId"]=ds["PassengerId"].fillna(ds["PassengerId"].mean())
print(ds)

ds["SibSp"]=ds["SibSp"].fillna(ds["SibSp"].mean())
print(ds)

import seaborn as sns
import matplotlib.pyplot as plt
sns.countplot(x="Survived", data=ds)
plt.title("Survival Counts")
plt.show()

sns.barplot(x="Sex", y="Survived", data=ds)
plt.title("Survival by Gender")
plt.show()

plt.hist(ds["Age"].dropna(), bins=20,color='g')
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Number of Passengers")
plt.show()

sns.scatterplot(x="Pclass", y="Fare", data=ds)
plt.title("Compare Fare by Passenger Class")
plt.show()

sns.boxplot(x="Age", y="Fare", data=ds)
plt.title("Compare Fare by Age")
plt.show()

sns.boxplot(y="Fare", data=ds)
plt.title("Fare Outliers")
plt.show()

ds.describe()

numeric_ds = ds.select_dtypes(include=["number"])
plt.figure(figsize=(8,6))
sns.heatmap(numeric_ds.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

